### ISSUE TITLE
转换时出现错误，项目是云函数方式。

### ISSUE THREAD

**Issue by smalike** [zhangdaren/miniprogram-to-uniapp#10]
转换时出现错误，项目是云函数方式。

项目结构如下：

```
minip
 -yunhanshu
 -src
  -pages
  -...
 -project.config.json
```

有些 vue 文件并没有转换出来，文件夹下是空的

```
(node:23136) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replaceWithMultiple' of null
    at handleSetData (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/jsHandle.js:84:11)
    at MemberExpression (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/jsHandle.js:176:6)
    at NodePath._call (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/path/context.js:95:18)
(node:23136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:23136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:23136) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replaceWithMultiple' of null
    at handleSetData (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/jsHandle.js:84:11)
    at MemberExpression (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/jsHandle.js:176:6)
    at NodePath._call (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/node_modules/@babel/traverse/lib/path/context.js:95:18)
(node:23136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by zhangdaren** [comment]
这个跟是否为云函数关系不大。可否提供没有转换成功的那个文件夹的js文件代码吗？方便定位问题，感谢~~

**Comment by smalike** [comment]
已经定位是这里的第 13 问题。 [https://github.com/zhangdaren/miniprogram-to-uniapp/issues/16](https://github.com/zhangdaren/miniprogram-to-uniapp/issues/16)
