### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dataAstList' of null

### ISSUE THREAD

**Issue by sususweet** [zhangdaren/miniprogram-to-uniapp#106]
转换vant小程序失败，日志如下：

(node:20892) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dataAstList' of null
    at addValueToData (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\project\attribHandle.js:202:46)
    at memberExpressionHandle (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\project\attribHandle.js:489:13)
    at MemberExpression (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\project\attribHandle.js:437:21)
    at NodePath._call (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:110:16)
    at TraversalContext.visitSingle (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:79:19)
    at TraversalContext.visit (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:138:19)
    at Function.traverse.node (C:\Users\sususweet\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\index.js:76:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:20892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Noliebe** [comment]
I have the same problem with you.
(node:23576) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dataAstList' of null

**Comment by sususweet** [comment]
谢谢，已经可以用了 @zhangdaren
