### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'buildError' of undefined 如何定位？

### ISSUE THREAD

**Issue by c4ys** [zhangdaren/miniprogram-to-uniapp#113]
### 问题描述？

转换过程中，出现以下错误，完全无法知道是哪里导致的

```
(node:14484) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'buildError' of undefined
    at Scope.checkBlockScopedCollisions (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\scope\index.js:421:22)
    at Scope.registerBinding (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\scope\index.js:581:16)
    at Scope.registerDeclaration (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\scope\index.js:523:14)
    at Object.Declaration (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\scope\index.js:177:12)
    at NodePath._call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:99:16)
    at TraversalContext.visitMultiple (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:68:17)
    at TraversalContext.visit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:125:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zhangdaren** [comment]
这个目测需要调试才能定位。。。目前在弄第二版，预计十一出来，，可以稍加等待吧，，

**Comment by zhangdaren** [comment]
请使用新版本工具尝试吧。
