### ISSUE TITLE
Unhandled Rejection at: Promise {   <rejected> RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rzshuo** [zhangdaren/miniprogram-to-uniapp#127]
### 问题描述？
[miniprogram to uniapp] 14:25:53.644 转换进度: 533 / 1408
[miniprogram to uniapp] 14:25:53.647 Unhandled Rejection at: Promise {
  <rejected> RangeError: Maximum call stack size exceeded
      at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/find.js:71:29
      at Array.every (<anonymous>)
      at checkIsMatch (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/find.js:11:33)
      at Object.handle (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/find.js:186:27)
      at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:46:23
      at Array.forEach (<anonymous>)
      at handleNode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:40:23)
      at traversChildnode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:142:29)
      at handleNode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:134:13)
      at traversChildnode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:142:29)
} reason: RangeError: Maximum call stack size exceeded
    at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/find.js:71:29
    at Array.every (<anonymous>)
    at checkIsMatch (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/find.js:11:33)
    at Object.handle (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/find.js:186:27)
    at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:46:23
    at Array.forEach (<anonymous>)
    at handleNode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:40:23)
    at traversChildnode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:142:29)
    at handleNode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:134:13)
    at traversChildnode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/miniprogram-to-uniapp/node_modules/gogocode/src/html-core/html-traverse.js:142:29)

### 重现步骤

转换就这样。

### 期望的结果

正常转

**Comment by rzshuo** [comment]
npm 版本 8.1

**Comment by rzshuo** [comment]
Duplicate of #57

**Comment by zhangdaren** [comment]
你这个与1.x的bug还不一样，，2.x是重写的。。可以远程让我定位一下？

**Comment by rzshuo** [comment]
> 

公司的电脑不好办，我已经放弃了uni了。

**Comment by zhangdaren** [comment]
> > 
> 
> 公司的电脑不好办，我已经放弃了uni了。

这就尴尬了
