### ISSUE TITLE
转换后遇到”格式化Error“报错，并且生成的uni项目中提示：“本项目类型无法运行到小程序模拟器”

### ISSUE THREAD

**Issue by ZhuningS** [zhangdaren/miniprogram-to-uniapp#144]
### 问题描述？
转换后遇到”格式化Error“报错，并且生成的uni项目中提示：“本项目类型无法运行到小程序模拟器”（右键重新识别类型一直是“web”，无法正常启动，也缺少根目录App.vue）
![image](https://user-images.githubusercontent.com/38108376/189986916-94d6477d-9b55-403a-a048-46972b19128e.png)
![image](https://user-images.githubusercontent.com/38108376/189986596-18cd75d0-8a24-4c31-affe-cf50ccb63e38.png)

### 重现步骤
wtu -i "C:\code\weixinmao_house 0822\"
报错如下：

进度 [##############################] 26/bps 99% 0.2s 格式化Error: fileKey: weixinmao_house/weixinmao_house/resource/wxParse/htmlparser     type:js       error： Error: Comment "Find the closest opened tag of the same type" was not printed. Please report this error!
    at Object._ [as ensureAllCommentsPrinted] (C:\Users\bing7\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\utils\prettier\standalone.js:41:7587)
    at b (C:\Users\bing7\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\utils\prettier\standalone.js:41:15205)
    at D (C:\Users\bing7\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\utils\prettier\standalone.js:45:576)    at C:\Users\bing7\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\utils\prettier\standalone.js:115:7299
    at Object.format (C:\Users\bing7\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\utils\prettier\standalone.js:115:7390)
    at formateByPrettier (C:\Users\bing7\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\utils\formatUtils.js:187:24)
    at Object.formatCode (C:\Users\bing7\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\utils\formatUtils.js:159:19)
    at Page.generate (C:\Users\bing7\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\page\index.js:691:39)
    at C:\Users\bing7\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\project\projectHandle.js:354:22
    at new Promise (<anonymous>)
进度 [##############################] 25/bps 100% 0.0s
![image](https://user-images.githubusercontent.com/38108376/189987640-d5509d7b-ea69-4bf6-a121-9f9e57118f26.png)
### 期望的结果
正常运行

**Comment by ZhuningS** [comment]
已解决，是项目目录层级问题。
