### ISSUE TITLE
在MAC上运行则报错ReferenceError: chalk is not defined

### ISSUE THREAD

**Issue by meiye1988** [zhangdaren/miniprogram-to-uniapp#2]
您好
本人按照https://ask.dcloud.net.cn/article/36037这个网址步骤去做
然后输入 wtu -i "xxxxxx"则报错如下
`➜  xiuxiuhuwx git:(master) ✗ wtu -i "xxxx"

/usr/local/lib/node_modules/miniprogram-to-uniapp/src/utils/utils.js:3
        return console.log(chalk.red(`[vue-to-react]: ${msg}`));
                           ^

ReferenceError: chalk is not defined
    at log (/usr/local/lib/node_modules/miniprogram-to-uniapp/src/utils/utils.js:3:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/miniprogram-to-uniapp/bin/wtu:45:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
`
不知道是什么原因，是否你这个工具只适合在win上

**Comment by zhangdaren** [comment]
暂未在mac上测试，这两天我测试一下。

**Comment by zhangdaren** [comment]
在mac上测试通过，这个是一个log日志功能报错的，现在请试试v1.0.9版本是否还有这个问题？

**Comment by cuiwang137** [comment]
> 在MAC上测试通过，这个是一个日志日志功能报错的，现在请试试v1.0.9版本是否还有这个问题？

1.0.9还是有这个问题

**Comment by cuiwang137** [comment]
> > 在MAC上测试通过，这个是一个日志日志功能报错的，现在请试试v1.0.9版本是否还有这个问题？
> 
> 1.0.9还是有这个问题

windows也出现这个问题

**Comment by liuxiaoyucc** [comment]
1.0.9版本 windows上,也遇到这个问题 
```
D:\install_dir\nodejs\node_global\node_modules\miniprogram-to-uniapp\src\utils\utils.js:3
        return console.log(chalk.red(`[vue-to-react]: ${msg}`));
                           ^

ReferenceError: chalk is not defined
    at log (D:\install_dir\nodejs\node_global\node_modules\miniprogram-to-uniapp\src\utils\utils.js:3:28)
    at Object.<anonymous> (D:\install_dir\nodejs\node_global\node_modules\miniprogram-to-uniapp\bin\wtu:45:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

C:\Users\Administrator>wtu -V
1.0.9
```

**Comment by wenxing158** [comment]
仍然这个问题

**Comment by zhangdaren** [comment]
是否影响正常使用了？


 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "wenxing158"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 下午3:53
收件人: "zhangdaren/miniprogram-to-uniapp"<miniprogram-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 在MAC上运行则报错ReferenceError: chalk is not defined (#2)




仍然这个问题
 
&mdash;

**Comment by cuiwang137** [comment]
一的影响正常使用

**Comment by cuiwang137** [comment]
是的  影响正常使用

**Comment by wenxing158** [comment]
是的，run不了转换代码，一跑就这样，感觉是不是chalk和其他package兼容性问题

**Comment by liuxiaoyucc** [comment]
> 是否影响正常使用了？
影响的,报错后转换停止

**Comment by zhangdaren** [comment]
已经修复了，请安装v1.0.10试试哈~~
 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "liuxy"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 下午3:58
收件人: "zhangdaren/miniprogram-to-uniap"<miniprogram-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 在MAC上运行则报错ReferenceError: chalk is not defined (#2)



 
是否影响正常使用了？
 影响的,报错后转换停止
  
&mdash;

**Comment by wenxing158** [comment]
👍
