### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by ph7pal** [zhangdaren/miniprogram-to-uniapp#3]
C:\Users\Administrator> wtu -V
C:\Program Files\nodejs\node_global\node_modules\miniprogram-to-uniapp\src\index.js:165
async function filesHandle(fileData) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files\nodejs\node_global\node_modules\miniprogram-to-uniapp\bin\wtu:8:19)

新安装的v1.0.7，成功后执行文档语句，报如上错误。谢谢辛苦查看。

**Comment by zhangdaren** [comment]
安装1.0.8试试？另外node版本是多少？

**Comment by ph7pal** [comment]
更新node之后可以了。感谢。
