### ISSUE TITLE
安装完包后wtu -v 报错

### ISSUE THREAD

**Issue by xiong16** [zhangdaren/miniprogram-to-uniapp#31]
xiong-MacBook-Pro:xiong xiong$ wtu -v
/usr/local/lib/node_modules/miniprogram-to-uniapp/src/index.js:297
async function filesHandle(fileData, miniprogramRoot) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/miniprogram-to-uniapp/bin/wtu:8:19)
    at Module._compile (module.js:570:32)

------------------------------
这个是什么问题？

**Comment by zhangdaren** [comment]
建议更新一下node版本哈~~需要v9以上
