### ISSUE TITLE
大神，报错无法转换

### ISSUE THREAD

**Issue by JsonWong87** [zhangdaren/miniprogram-to-uniapp#55]
>wtu -i C:\Users\Administrator\Desktop\higocountry -o C:\Users\Administrator\Desktop\higoCNew
C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:254
                                                                                (async function (fileDir, newFileDir) {
                                                                                       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\bin\wtu:8:19)

**Comment by zhangdaren** [comment]
这个是node的版本略低，不支持新的JS语法。
请升级一下node的版本哈
