### ISSUE TITLE
提示错误信息

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#57]
'(node:44044) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at Object.get [as VISITOR_KEYS] (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\types\lib\definitions\index.js:8:17)
    at Object.get [as VISITOR_KEYS] (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\types\lib\index.js:496:26)
    at Function.traverse.node (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\index.js:78:18)
    at NodePath.visit (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:97:18)
    at TraversalContext.visitQueue (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitSingle (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:84:19)
    at TraversalContext.visit (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:140:19)
    at Function.traverse.node (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\index.js:84:17)
    at NodePath.visit (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:97:18)
    at TraversalContext.visitQueue (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:112:16)
(node:44044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:44044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.'

**Comment by zhangdaren** [comment]
似乎没有一行是工具是里面的报错，，可以定位是哪个文件里报错的嘛？看起来像是解析js文件时报的错。

**Comment by zhangdaren** [comment]
把我手头的小程序源码，20+个都测了一遍，没有出现这个问题，1.0.47版

**Comment by rzshuo** [comment]
我也报这个。mac端 v2.0.9
