### ISSUE TITLE
转换失败

### ISSUE THREAD

**Issue by a1664670118** [zhangdaren/miniprogram-to-uniapp#60]
template里的data属性 ==> "{{...item, index}}"     需要替换的属性 ==> {}
template里的data属性 ==> "{{...item, index}}"     需要替换的属性 ==> {}
(node:10596) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (38:1)
    at Parser.raise (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:7013:17)
    at Parser.unexpected (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8384:16)
    at Parser.expect (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8370:28)
    at Parser.parseObj (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9954:14)
    at Parser.parseExprAtom (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9582:28)
    at Parser.parseExprSubscripts (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9219:23)
    at Parser.parseMaybeUnary (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9199:21)
    at Parser.parseExprOps (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9067:23)
    at Parser.parseMaybeConditional (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9040:23)
    at Parser.parseMaybeAssign (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9000:21)
(node:10596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10596) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (38:1)
    at Parser.raise (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:7013:17)
    at Parser.unexpected (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8384:16)
    at Parser.expect (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8370:28)
    at Parser.parseObj (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9954:14)
    at Parser.parseExprAtom (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9582:28)
    at Parser.parseExprSubscripts (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9219:23)
    at Parser.parseMaybeUnary (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9199:21)
    at Parser.parseExprOps (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9067:23)
    at Parser.parseMaybeConditional (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9040:23)
    at Parser.parseMaybeAssign (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9000:21)
(node:10596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:10596) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (38:1)
    at Parser.raise (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:7013:17)
    at Parser.unexpected (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8384:16)
    at Parser.expect (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8370:28)
    at Parser.parseObj (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9954:14)
    at Parser.parseExprAtom (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9582:28)
    at Parser.parseExprSubscripts (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9219:23)
    at Parser.parseMaybeUnary (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9199:21)
    at Parser.parseExprOps (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9067:23)
    at Parser.parseMaybeConditional (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9040:23)
    at Parser.parseMaybeAssign (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9000:21)
(node:10596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:10596) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (38:1)
    at Parser.raise (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:7013:17)
    at Parser.unexpected (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8384:16)
    at Parser.expect (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8370:28)
    at Parser.parseObj (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9954:14)
    at Parser.parseExprAtom (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9582:28)
    at Parser.parseExprSubscripts (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9219:23)
    at Parser.parseMaybeUnary (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9199:21)
    at Parser.parseExprOps (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9067:23)
    at Parser.parseMaybeConditional (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9040:23)
    at Parser.parseMaybeAssign (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9000:21)
(node:10596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:10596) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (38:1)
    at Parser.raise (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:7013:17)
    at Parser.unexpected (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8384:16)
    at Parser.expect (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8370:28)
    at Parser.parseObj (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9954:14)
    at Parser.parseExprAtom (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9582:28)
    at Parser.parseExprSubscripts (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9219:23)
    at Parser.parseMaybeUnary (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9199:21)
    at Parser.parseExprOps (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9067:23)
    at Parser.parseMaybeConditional (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9040:23)
    at Parser.parseMaybeAssign (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9000:21)
(node:10596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:10596) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (38:1)
    at Parser.raise (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:7013:17)
    at Parser.unexpected (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8384:16)
    at Parser.expect (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8370:28)
    at Parser.parseObj (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9954:14)
    at Parser.parseExprAtom (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9582:28)
    at Parser.parseExprSubscripts (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9219:23)
    at Parser.parseMaybeUnary (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9199:21)
    at Parser.parseExprOps (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9067:23)
    at Parser.parseMaybeConditional (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9040:23)
    at Parser.parseMaybeAssign (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9000:21)
(node:10596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:10596) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (38:1)
    at Parser.raise (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:7013:17)
    at Parser.unexpected (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8384:16)
    at Parser.expect (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8370:28)
    at Parser.parseObj (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9954:14)
    at Parser.parseExprAtom (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9582:28)
    at Parser.parseExprSubscripts (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9219:23)
    at Parser.parseMaybeUnary (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9199:21)
    at Parser.parseExprOps (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9067:23)
    at Parser.parseMaybeConditional (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9040:23)
    at Parser.parseMaybeAssign (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9000:21)
(node:10596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:10596) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (38:1)
    at Parser.raise (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:7013:17)
    at Parser.unexpected (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8384:16)
    at Parser.expect (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:8370:28)
    at Parser.parseObj (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9954:14)
    at Parser.parseExprAtom (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9582:28)
    at Parser.parseExprSubscripts (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9219:23)
    at Parser.parseMaybeUnary (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9199:21)
    at Parser.parseExprOps (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9067:23)
    at Parser.parseMaybeConditional (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9040:23)
    at Parser.parseMaybeAssign (C:\Users\Administrator\AppData\Roaming\nvm\v10.16.2\node_modules\miniprogram-to-uniapp\node_modules\@babel\parser\lib\index.js:9000:21)
(node:10596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
Convert app.css success!

**Comment by zhangdaren** [comment]
找到原因了，，51版本解决。。即将更新。
