### ISSUE TITLE
转换后只有CSS文件

### ISSUE THREAD

**Issue by 971768966** [zhangdaren/miniprogram-to-uniapp#84]
wtu版本1.0.74

项目进行转换后只有每个文件的css文件，其他的都没有转换成功

log报错：

(node:9744) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'properties' of undefined
    at lifeCycleHandle (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\js\componentConverter.js:229:40)
    at ObjectMethod (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\js\componentConverter.js:209:5)
    at NodePath._call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:92:31)
    at TraversalContext.visitQueue (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitMultiple (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:79:17)
    at TraversalContext.visit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\context.js:138:19)
    at Function.traverse.node (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\index.js:82:17)
    at NodePath.visit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\node_modules\@babel\traverse\lib\path\context.js:99:18)
(node:9744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zhangdaren** [comment]
可以提供一下项目给我看看吗？ 大概知道是哪里的问题，，想要复现一下可以提供一下项目给我看看吗？ 大概知道是哪里的问题，，想要复现一下

**Comment by zhangdaren** [comment]
v1.1.1现在应该没这个问题了
